// thumbs.rs — `thumb://localhost/<id>/<size>`: a JPEG thumbnail of any
// photo the catalog knows, cached on disk and generated by ImageIO off the
// main thread. One code path covers JPEG, HEIC and every RAW format ImageIO
// decodes; RAWs use their embedded preview so nothing demosaics a 40 MB file.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Condvar, Mutex};

use objc2_core_foundation::{
    CFBoolean, CFDictionary, CFNumber, CFRetained, CFString, CFType, CFURLPathStyle, CFURL,
};
use objc2_image_io::{
    kCGImageDestinationLossyCompressionQuality, kCGImageSourceCreateThumbnailFromImageAlways,
    kCGImageSourceCreateThumbnailFromImageIfAbsent, kCGImageSourceCreateThumbnailWithTransform,
    kCGImageSourceShouldCache, kCGImageSourceThumbnailMaxPixelSize, CGImageDestination,
    CGImageSource,
};
use sha2::{Digest, Sha256};
use tauri::http::{header, Request, Response, StatusCode};
use tauri::{Manager, Runtime, UriSchemeContext, UriSchemeResponder};

use crate::catalog::walk::is_raw;
use crate::state::{AppState, Entry};
use crate::volumes::VolumeKind;

/// Longest edge in pixels: 512 for calendar cells and shredder strips, 1600 for the deck card.
pub const SIZES: [u32; 2] = [512, 1600];
const POOL_THREADS: usize = 4;
/// Card readers are slow and serial; more parallel reads only thrash.
const CARD_READERS: usize = 2;
const JPEG_QUALITY: f64 = 0.8;

pub struct Thumbnailer {
    dir: PathBuf,
    pool: rayon::ThreadPool,
    card_gate: Gate,
}

impl Thumbnailer {
    pub fn new(dir: PathBuf) -> Self {
        let _ = fs::create_dir_all(&dir);
        let pool = rayon::ThreadPoolBuilder::new()
            .num_threads(POOL_THREADS)
            .thread_name(|i| format!("thumb-{i}"))
            .build()
            .expect("thumbnail thread pool");
        Thumbnailer { dir, pool, card_gate: Gate::new(CARD_READERS) }
    }

    /// `<dir>/<sha256(path|size|mtime)>-<size>.jpg`; the mtime in the key
    /// makes an edited original miss the cache without any invalidation logic.
    pub fn cache_path(&self, path: &Path, size: u32, mtime: u64) -> PathBuf {
        let digest = Sha256::digest(format!("{}|{}|{}", path.display(), size, mtime).as_bytes());
        self.dir.join(format!("{}-{}.jpg", hex::encode(digest), size))
    }

    /// Drops both cached sizes of a file as it was at `mtime`. A metadata edit
    /// needs this: the key has no file size in it, and retag restores the
    /// mtime of photos dated by it, so the old orientation would keep serving.
    pub fn evict(&self, path: &Path, mtime: u64) {
        for size in SIZES {
            let _ = fs::remove_file(self.cache_path(path, size, mtime));
        }
    }

    /// Blocking: returns the cached thumbnail, generating it first when absent.
    pub fn ensure(&self, entry: &Entry, size: u32) -> Result<PathBuf, String> {
        let out = self.cache_path(&entry.path, size, entry.mtime);
        if out.is_file() {
            return Ok(out);
        }
        let _permit = (entry.kind == VolumeKind::Card).then(|| self.card_gate.acquire());
        generate(&entry.path, size, &out)?;
        Ok(out)
    }
}

/// Runs `job` on the thumbnail pool with the shared state kept alive for it.
pub fn spawn(state: Arc<AppState>, job: impl FnOnce(&AppState) + Send + 'static) {
    let pool_owner = Arc::clone(&state);
    pool_owner.thumbs.pool.spawn(move || job(&state));
}

/// Warms the cache for the ids the deck is about to show.
pub fn prefetch(state: Arc<AppState>, ids: Vec<String>, size: u32) {
    for id in ids {
        let Some(entry) = state.entry(&id) else { continue };
        spawn(Arc::clone(&state), move |st| {
            let _ = st.thumbs.ensure(&entry, size);
        });
    }
}

/// The `thumb` scheme handler. Returns immediately; the response is produced
/// on the pool, so the webview's protocol thread never waits on a card.
pub fn handle<R: Runtime>(ctx: UriSchemeContext<'_, R>, request: Request<Vec<u8>>, responder: UriSchemeResponder) {
    let Some(state) = ctx.app_handle().try_state::<Arc<AppState>>().map(|s| Arc::clone(s.inner())) else {
        return responder.respond(plain(StatusCode::SERVICE_UNAVAILABLE, "state not ready"));
    };
    let Some((id, size)) = parse_path(request.uri().path()) else {
        return responder.respond(plain(StatusCode::BAD_REQUEST, "expected /<id>/<512|1600>"));
    };
    let Some(entry) = state.entry(&id) else {
        return responder.respond(plain(StatusCode::NOT_FOUND, "unknown photo id"));
    };
    spawn(state, move |st| {
        let result = st
            .thumbs
            .ensure(&entry, size)
            .and_then(|p| fs::read(&p).map_err(|e| e.to_string()));
        responder.respond(match result {
            Ok(bytes) => jpeg(bytes),
            Err(message) => plain(StatusCode::INTERNAL_SERVER_ERROR, &message),
        });
    });
}

/// `/<id>/<size>` → (id, size), size restricted to the two we cache. The
/// frontend appends `?o=<orientation>` so the webview's URL cache misses after
/// a rotation; that query never reaches here (`uri().path()` excludes it).
fn parse_path(path: &str) -> Option<(String, u32)> {
    let mut parts = path.trim_matches('/').split('/');
    let id = parts.next().filter(|s| !s.is_empty())?;
    let size: u32 = parts.next()?.parse().ok()?;
    if parts.next().is_some() || !SIZES.contains(&size) {
        return None;
    }
    Some((id.to_string(), size))
}

fn jpeg(bytes: Vec<u8>) -> Response<Vec<u8>> {
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "image/jpeg")
        .header(header::CACHE_CONTROL, "public, max-age=31536000, immutable")
        .header(header::ACCESS_CONTROL_ALLOW_ORIGIN, "*")
        .body(bytes)
        .expect("static headers")
}

fn plain(status: StatusCode, message: &str) -> Response<Vec<u8>> {
    Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "text/plain")
        .header(header::ACCESS_CONTROL_ALLOW_ORIGIN, "*")
        .body(message.as_bytes().to_vec())
        .expect("static headers")
}

/// ImageIO: open → thumbnail (orientation applied, longest edge ≤ size) →
/// JPEG. Written to a temp name and renamed so a concurrent reader never sees
/// a half-written cache file.
pub(crate) fn generate(src: &Path, size: u32, out: &Path) -> Result<(), String> {
    if let Some(dir) = out.parent() {
        fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let tmp = out.with_extension(format!("{:x}.part", rayon::current_thread_index().unwrap_or(0)));

    // SAFETY: every call below is a plain ImageIO / CoreFoundation function
    // fed CF objects we own; the dictionaries hold CFStrings keyed to the
    // CFBoolean / CFNumber values those keys document.
    unsafe {
        let source_opts = dict(&[kCGImageSourceShouldCache], &[CFBoolean::new(false)]);
        let src_url = file_url(src)?;
        let source = CGImageSource::with_url(&src_url, Some(source_opts.as_opaque()))
            .ok_or("ImageIO cannot open the file")?;

        // A camera JPEG embeds a 160 px thumbnail, useless at 512; decode the
        // image (ImageIO subsamples, so this is cheap). A RAW embeds a large
        // preview, which is exactly what we want instead of demosaicing.
        let mode = if is_raw(src) {
            kCGImageSourceCreateThumbnailFromImageIfAbsent
        } else {
            kCGImageSourceCreateThumbnailFromImageAlways
        };
        let max = CFNumber::new_i32(size as i32);
        let yes: &CFType = CFBoolean::new(true);
        let thumb_opts = dict(
            &[mode, kCGImageSourceThumbnailMaxPixelSize, kCGImageSourceCreateThumbnailWithTransform],
            &[yes, &max, yes],
        );
        let image = source
            .thumbnail_at_index(0, Some(thumb_opts.as_opaque()))
            .ok_or("ImageIO cannot decode the image")?;

        let jpeg_type = CFString::from_static_str("public.jpeg");
        let tmp_url = file_url(&tmp)?;
        let dest = CGImageDestination::with_url(&tmp_url, &jpeg_type, 1, None)
            .ok_or("cannot create the cache file")?;
        let quality = CFNumber::new_f64(JPEG_QUALITY);
        let dest_opts = dict(&[kCGImageDestinationLossyCompressionQuality], &[&quality]);
        dest.add_image(&image, Some(dest_opts.as_opaque()));
        if !dest.finalize() {
            let _ = fs::remove_file(&tmp);
            return Err("JPEG encoding failed".into());
        }
    }
    fs::rename(&tmp, out).map_err(|e| e.to_string())
}

fn dict(keys: &[&CFString], values: &[&CFType]) -> CFRetained<CFDictionary<CFString, CFType>> {
    CFDictionary::from_slices(keys, values)
}

fn file_url(path: &Path) -> Result<CFRetained<CFURL>, String> {
    let string = CFString::from_str(&path.to_string_lossy());
    CFURL::with_file_system_path(None, Some(&string), CFURLPathStyle::CFURLPOSIXPathStyle, false)
        .ok_or_else(|| format!("not a file URL: {}", path.display()))
}

/// Counting semaphore; std has none and tokio's would drag async into the pool.
struct Gate {
    permits: Mutex<usize>,
    released: Condvar,
}

struct Permit<'a>(&'a Gate);

impl Gate {
    fn new(permits: usize) -> Self {
        Gate { permits: Mutex::new(permits), released: Condvar::new() }
    }

    fn acquire(&self) -> Permit<'_> {
        let mut free = self.permits.lock().unwrap_or_else(|e| e.into_inner());
        while *free == 0 {
            free = self.released.wait(free).unwrap_or_else(|e| e.into_inner());
        }
        *free -= 1;
        Permit(self)
    }
}

impl Drop for Permit<'_> {
    fn drop(&mut self) {
        *self.0.permits.lock().unwrap_or_else(|e| e.into_inner()) += 1;
        self.0.released.notify_one();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_only_well_formed_paths() {
        assert_eq!(parse_path("/abc123/512"), Some(("abc123".into(), 512)));
        assert_eq!(parse_path("/abc123/1600"), Some(("abc123".into(), 1600)));
        assert_eq!(parse_path("/abc123/300"), None);
        assert_eq!(parse_path("/abc123"), None);
        assert_eq!(parse_path("/abc123/512/extra"), None);
        assert_eq!(parse_path("//512"), None);
    }

    #[test]
    fn query_string_does_not_reach_the_path_parser() {
        let request = Request::builder().uri("thumb://localhost/abc123/1600?o=6").body(Vec::<u8>::new()).unwrap();
        assert_eq!(parse_path(request.uri().path()), Some(("abc123".into(), 1600)));
    }

    #[test]
    fn evict_removes_both_sizes_for_that_mtime_only() {
        let dir = tempfile::tempdir().unwrap();
        let t = Thumbnailer::new(dir.path().join("thumbs"));
        let p = Path::new("/a.jpg");
        for (size, mtime) in [(512, 1), (1600, 1), (512, 2)] {
            fs::write(t.cache_path(p, size, mtime), b"x").unwrap();
        }
        t.evict(p, 1);
        assert!(!t.cache_path(p, 512, 1).exists());
        assert!(!t.cache_path(p, 1600, 1).exists());
        assert!(t.cache_path(p, 512, 2).exists());
    }

    #[test]
    fn cache_path_changes_with_every_key_part() {
        let t = Thumbnailer::new(tempfile::tempdir().unwrap().path().join("thumbs"));
        let p = Path::new("/a.jpg");
        assert_eq!(t.cache_path(p, 512, 1), t.cache_path(p, 512, 1));
        assert_ne!(t.cache_path(p, 512, 1), t.cache_path(p, 1600, 1));
        assert_ne!(t.cache_path(p, 512, 1), t.cache_path(p, 512, 2));
        assert!(t.cache_path(p, 512, 1).to_string_lossy().ends_with("-512.jpg"));
    }

    /// Real ImageIO on a system wallpaper (HEIC, 30 MB): proves the CF option
    /// dictionaries are typed right and the JPEG lands within the size cap.
    #[test]
    fn imageio_thumbnails_a_system_heic() {
        let src = Path::new("/System/Library/Desktop Pictures/Big Sur Graphic.heic");
        if !src.is_file() {
            eprintln!("skipped: no system HEIC on this machine");
            return;
        }
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("thumbs").join("x-512.jpg");
        generate(src, 512, &out).unwrap();
        let bytes = fs::read(&out).unwrap();
        assert_eq!(&bytes[..2], &[0xFF, 0xD8], "not a JPEG");
        let size = imagesize::blob_size(&bytes).unwrap();
        assert!(size.width.max(size.height) <= 512, "{size:?}");
        assert!(size.width.max(size.height) >= 500, "{size:?}");
        assert!(!dir.path().join("thumbs").join("x-512.0.part").exists());
    }

    #[test]
    fn gate_limits_concurrency() {
        let gate = Gate::new(1);
        let first = gate.acquire();
        assert_eq!(*gate.permits.lock().unwrap(), 0);
        drop(first);
        assert_eq!(*gate.permits.lock().unwrap(), 1);
    }
}
